/**
 * Brand Profiles API Routes
 * Manages brand profiles for multi-client agencies and solo users
 */

const express = require('express');
const router = express.Router();
const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY;

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: { autoRefreshToken: false, persistSession: false }
});

// Middleware to verify authentication
const authenticate = async (req, res, next) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'No authorization token provided' });
  }

  const token = authHeader.substring(7);
  const { data: { user }, error } = await supabase.auth.getUser(token);

  if (error || !user) {
    return res.status(401).json({ error: 'Invalid or expired token' });
  }

  req.user = user;
  next();
};

// ============================================
// GET /api/brands - List all brands for user
// ============================================
router.get('/', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;

    // Get brands owned by user OR their team
    const { data: brands, error } = await supabase
      .from('brand_profile_stats')
      .select('*')
      .or(`user_id.eq.${userId},team_id.in.(select team_id from team_members where user_id='${userId}')`)
      .eq('is_active', true)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching brands:', error);
      return res.status(500).json({ error: 'Failed to fetch brands' });
    }

    res.json({ brands: brands || [] });
  } catch (error) {
    console.error('Error in GET /api/brands:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// GET /api/brands/:id - Get single brand
// ============================================
router.get('/:id', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const brandId = req.params.id;

    const { data: brand, error } = await supabase
      .from('brand_profile_stats')
      .select('*')
      .eq('id', brandId)
      .or(`user_id.eq.${userId},team_id.in.(select team_id from team_members where user_id='${userId}')`)
      .single();

    if (error) {
      console.error('Error fetching brand:', error);
      return res.status(404).json({ error: 'Brand not found' });
    }

    res.json({ brand });
  } catch (error) {
    console.error('Error in GET /api/brands/:id:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// POST /api/brands - Create new brand
// ============================================
router.post('/', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const {
      name,
      description,
      team_id,
      brand_voice,
      logo_url,
      brand_colors
    } = req.body;

    if (!name) {
      return res.status(400).json({ error: 'Brand name is required' });
    }

    // Create brand (slug auto-generated by trigger)
    const brandData = {
      name,
      description: description || null,
      user_id: team_id ? null : userId, // If team, user_id is null
      team_id: team_id || null,         // If no team, team_id is null
      brand_voice: brand_voice || {},
      logo_url: logo_url || null,
      brand_colors: brand_colors || [],
      is_active: true
    };

    const { data: brand, error } = await supabase
      .from('brand_profiles')
      .insert([brandData])
      .select()
      .single();

    if (error) {
      console.error('Error creating brand:', error);
      return res.status(500).json({ error: 'Failed to create brand' });
    }

    res.status(201).json({ brand });
  } catch (error) {
    console.error('Error in POST /api/brands:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// PUT /api/brands/:id - Update brand
// ============================================
router.put('/:id', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const brandId = req.params.id;
    const {
      name,
      description,
      brand_voice,
      logo_url,
      brand_colors,
      is_active
    } = req.body;

    // Check if user can manage this brand
    const { data: canManage } = await supabase
      .rpc('user_can_manage_brand', {
        p_user_id: userId,
        p_brand_id: parseInt(brandId)
      });

    if (!canManage) {
      return res.status(403).json({ error: 'You do not have permission to update this brand' });
    }

    const updateData = {};
    if (name !== undefined) updateData.name = name;
    if (description !== undefined) updateData.description = description;
    if (brand_voice !== undefined) updateData.brand_voice = brand_voice;
    if (logo_url !== undefined) updateData.logo_url = logo_url;
    if (brand_colors !== undefined) updateData.brand_colors = brand_colors;
    if (is_active !== undefined) updateData.is_active = is_active;

    const { data: brand, error } = await supabase
      .from('brand_profiles')
      .update(updateData)
      .eq('id', brandId)
      .select()
      .single();

    if (error) {
      console.error('Error updating brand:', error);
      return res.status(500).json({ error: 'Failed to update brand' });
    }

    res.json({ brand });
  } catch (error) {
    console.error('Error in PUT /api/brands/:id:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// DELETE /api/brands/:id - Delete brand
// ============================================
router.delete('/:id', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const brandId = req.params.id;

    // Check if user can manage this brand
    const { data: canManage } = await supabase
      .rpc('user_can_manage_brand', {
        p_user_id: userId,
        p_brand_id: parseInt(brandId)
      });

    if (!canManage) {
      return res.status(403).json({ error: 'You do not have permission to delete this brand' });
    }

    const { error } = await supabase
      .from('brand_profiles')
      .delete()
      .eq('id', brandId);

    if (error) {
      console.error('Error deleting brand:', error);
      return res.status(500).json({ error: 'Failed to delete brand' });
    }

    res.json({ message: 'Brand deleted successfully' });
  } catch (error) {
    console.error('Error in DELETE /api/brands/:id:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// GET /api/brands/:id/accounts - Get brand's social accounts
// ============================================
router.get('/:id/accounts', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const brandId = req.params.id;

    // Verify user can access this brand
    const { data: brand } = await supabase
      .from('brand_profiles')
      .select('id')
      .eq('id', brandId)
      .or(`user_id.eq.${userId},team_id.in.(select team_id from team_members where user_id='${userId}')`)
      .single();

    if (!brand) {
      return res.status(404).json({ error: 'Brand not found' });
    }

    // Get all social accounts for this brand
    const [fbAccounts, igAccounts, ttAccounts] = await Promise.all([
      supabase.from('facebook_accounts').select('*').eq('brand_profile_id', brandId),
      supabase.from('instagram_accounts').select('*').eq('brand_profile_id', brandId),
      supabase.from('tiktok_accounts').select('*').eq('brand_profile_id', brandId)
    ]);

    const accounts = {
      facebook: fbAccounts.data || [],
      instagram: igAccounts.data || [],
      tiktok: ttAccounts.data || []
    };

    res.json({ accounts });
  } catch (error) {
    console.error('Error in GET /api/brands/:id/accounts:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// POST /api/brands/:id/accounts/:platform/:accountId - Link account to brand
// ============================================
router.post('/:id/accounts/:platform/:accountId', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const { id: brandId, platform, accountId } = req.params;

    // Check if user can manage this brand
    const { data: canManage } = await supabase
      .rpc('user_can_manage_brand', {
        p_user_id: userId,
        p_brand_id: parseInt(brandId)
      });

    if (!canManage) {
      return res.status(403).json({ error: 'You do not have permission to manage this brand' });
    }

    // Determine the table name
    const tableMap = {
      facebook: 'facebook_accounts',
      instagram: 'instagram_accounts',
      tiktok: 'tiktok_accounts'
    };

    const tableName = tableMap[platform];
    if (!tableName) {
      return res.status(400).json({ error: 'Invalid platform' });
    }

    // Update the account
    const { data: account, error } = await supabase
      .from(tableName)
      .update({ brand_profile_id: brandId })
      .eq('id', accountId)
      .eq('user_id', userId)
      .select()
      .single();

    if (error) {
      console.error('Error linking account to brand:', error);
      return res.status(500).json({ error: 'Failed to link account to brand' });
    }

    res.json({ account });
  } catch (error) {
    console.error('Error in POST /api/brands/:id/accounts/:platform/:accountId:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// ============================================
// DELETE /api/brands/:id/accounts/:platform/:accountId - Unlink account from brand
// ============================================
router.delete('/:id/accounts/:platform/:accountId', authenticate, async (req, res) => {
  try {
    const userId = req.user.id;
    const { id: brandId, platform, accountId } = req.params;

    // Check if user can manage this brand
    const { data: canManage } = await supabase
      .rpc('user_can_manage_brand', {
        p_user_id: userId,
        p_brand_id: parseInt(brandId)
      });

    if (!canManage) {
      return res.status(403).json({ error: 'You do not have permission to manage this brand' });
    }

    // Determine the table name
    const tableMap = {
      facebook: 'facebook_accounts',
      instagram: 'instagram_accounts',
      tiktok: 'tiktok_accounts'
    };

    const tableName = tableMap[platform];
    if (!tableName) {
      return res.status(400).json({ error: 'Invalid platform' });
    }

    // Update the account (set brand_profile_id to null)
    const { data: account, error } = await supabase
      .from(tableName)
      .update({ brand_profile_id: null })
      .eq('id', accountId)
      .eq('brand_profile_id', brandId)
      .select()
      .single();

    if (error) {
      console.error('Error unlinking account from brand:', error);
      return res.status(500).json({ error: 'Failed to unlink account from brand' });
    }

    res.json({ account });
  } catch (error) {
    console.error('Error in DELETE /api/brands/:id/accounts/:platform/:accountId:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

module.exports = router;
